### ISSUE TITLE
/bin/sh: 1: /usr/local/bin/start-xvfb-nginx.sh: not found

### ISSUE THREAD

**Issue by lowlyocean** [opengisch/qgis-docker#76]
Installed latest docker-desktop as well as heroku-cli via Chocolately in Win10

After cloning the repo, this error happens when running image produced via `heroku container:push` and `heroku container:release`

**Comment by CowboyCoderForever** [comment]
I've seen this as well. It stems from developing between Windows and Linux.
I think there are two problems:
* the `start-xvfb-nginx.sh` file permissions (it needs the "+x" set)
* the `start-xvfb-nginx.sh` line endings need to be "LF", not "CRLF" as Windows likes.

I think I have this fixed by modifying the Dockerfile as such:
```
...
ADD start-xvfb-nginx.sh /usr/local/bin/start-xvfb-nginx.sh
RUN chmod +x /usr/local/bin/start-xvfb-nginx.sh
...
```
And by ensuring the `start-xvfb-nginx.sh` is checked out with "LF" line endings before building the Docker image.
